//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// EquipmentItem defines model for EquipmentItem.
type EquipmentItem struct {
	Id                 *openapi_types.UUID `json:"id,omitempty"`
	Name               *string             `json:"name,omitempty"`
	VibrationMagnitude *float32            `json:"vibration_magnitude,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error A short, machine-readable error slug
	Error *string `json:"error,omitempty"`

	// Message A human-readable description of the error
	Message *string `json:"message,omitempty"`
}

// Exposure defines model for Exposure.
type Exposure struct {
	// A8 The A8 value for the exposure
	A8 *float32 `json:"a8,omitempty"`

	// Duration The duration of the exposure (in minutes)
	Duration  *int                `json:"duration,omitempty"`
	Equipment *EquipmentItem      `json:"equipment,omitempty"`
	Id        *openapi_types.UUID `json:"id,omitempty"`

	// Points The partial exposure of points
	Points *float32 `json:"points,omitempty"`
	User   *User    `json:"user,omitempty"`
}

// ExposureSummary defines model for ExposureSummary.
type ExposureSummary struct {
	// A8 The A8 value for the exposure
	A8 *float32 `json:"a8,omitempty"`

	// Points The partial exposure of points
	Points *float32 `json:"points,omitempty"`
	User   *User    `json:"user,omitempty"`
}

// User defines model for User.
type User struct {
	Id   *openapi_types.UUID `json:"id,omitempty"`
	Name *string             `json:"name,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = ErrorResponse

// ExposurePost defines model for ExposurePost.
type ExposurePost struct {
	// Duration The duration of the exposure (in minutes)
	Duration    *int                `json:"duration,omitempty"`
	EquipmentId *openapi_types.UUID `json:"equipment_id,omitempty"`
	UserId      *openapi_types.UUID `json:"user_id,omitempty"`
}

// RecordExposureJSONBody defines parameters for RecordExposure.
type RecordExposureJSONBody struct {
	// Duration The duration of the exposure (in minutes)
	Duration    *int                `json:"duration,omitempty"`
	EquipmentId *openapi_types.UUID `json:"equipment_id,omitempty"`
	UserId      *openapi_types.UUID `json:"user_id,omitempty"`
}

// GetUserExposureSummaryParams defines parameters for GetUserExposureSummary.
type GetUserExposureSummaryParams struct {
	StartingAt *time.Time `form:"starting_at,omitempty" json:"starting_at,omitempty"`
	EndingAt   *time.Time `form:"ending_at,omitempty" json:"ending_at,omitempty"`
}

// RecordExposureJSONRequestBody defines body for RecordExposure for application/json ContentType.
type RecordExposureJSONRequestBody RecordExposureJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Retrieve a collection of exposure resources
	// (GET /exposure)
	GetExposures(w http.ResponseWriter, r *http.Request)
	// Record an exposure
	// (POST /exposure)
	RecordExposure(w http.ResponseWriter, r *http.Request)
	// Retrieve an exposure resource
	// (GET /exposure/{exposureId})
	GetExposure(w http.ResponseWriter, r *http.Request, exposureId openapi_types.UUID)
	// Retrieve the exposure summary for a user
	// (GET /users/{userId}/exposure-summary)
	GetUserExposureSummary(w http.ResponseWriter, r *http.Request, userId openapi_types.UUID, params GetUserExposureSummaryParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetExposures operation middleware
func (siw *ServerInterfaceWrapper) GetExposures(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExposures(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordExposure operation middleware
func (siw *ServerInterfaceWrapper) RecordExposure(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordExposure(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetExposure operation middleware
func (siw *ServerInterfaceWrapper) GetExposure(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "exposureId" -------------
	var exposureId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "exposureId", r.PathValue("exposureId"), &exposureId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "exposureId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExposure(w, r, exposureId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUserExposureSummary operation middleware
func (siw *ServerInterfaceWrapper) GetUserExposureSummary(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "userId" -------------
	var userId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "userId", r.PathValue("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserExposureSummaryParams

	// ------------- Optional query parameter "starting_at" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "starting_at", r.URL.Query(), &params.StartingAt, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "starting_at"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "starting_at", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "ending_at" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "ending_at", r.URL.Query(), &params.EndingAt, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "ending_at"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ending_at", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUserExposureSummary(w, r, userId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/exposure", wrapper.GetExposures)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/exposure", wrapper.RecordExposure)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/exposure/{exposureId}", wrapper.GetExposure)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/users/{userId}/exposure-summary", wrapper.GetUserExposureSummary)

	return m
}
